name: 'AWS CLI action'

description: 'Github Action to execute AWS CLI commands'

inputs:
    args:
        description: 'AWS arguments'
        required: true
        default: 's3 ls'

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.args }}

branding:
    icon: 'terminal'
    color: 'orange'