name: 'AWS CLIs (V1 & V2) Action'

description: 'Github Action to use any version (1.x.y or 2.x.y) of AWS CLI to run any AWS CLI commands on your workflows 🤖'

inputs:
    args:
        description: 'AWS arguments'
        required: true
        default: 's3 ls'

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.args }}

branding:
    icon: 'terminal'
    color: 'orange'
