
name: AWS CLI V2.X.Y action

on:
  push:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
    
  job-aws-cli-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Run AWS CLI v2.2.0 commands
        uses: GuillaumeFalourd/aws-cli-action@main
        env:
          AWS_CLI_VERSION: "2.2.0" # If not informed, the latest AWS CLI version 2 will be used.
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
        with:
          args: s3 ls