
name: AWS CLI Latest Version action

on:
  push:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
    
  job-aws-cli-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Run AWS CLI latest version commands
        uses: GuillaumeFalourd/aws-cli-action@main
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
        with:
          args: s3 ls
